Sequences = {
    Tobacco = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Prop', Model = 'prop_cs_ciggy_01', Bone = 28422, Offset = vector3(0.01, 0.0, 0.0), Rotation = vector3(0.0, 0.0, 0.0)},
        {Type = 'Animation', Dict = 'amb@world_human_smoking@male@male_a@enter', Anim = 'enter', Flag = 49, Duration = 11000},
        {Type = 'Playing', Boolean = false},
        {Type = 'Prop', Model = 'prop_cs_ciggy_01', Stop = true},
        {Type = 'ScreenEffect', Effect = 'CamPushInNeutral', Duration = 1000},
        {Type = 'ScreenEffect', Stop = true}
    },
    Weed = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Prop', Model = 'p_cs_joint_01', Bone = 28422, Offset = vector3(0.01, 0.0, 0.0), Rotation = vector3(0.0, 0.0, 0.0)},
        {Type = 'Animation', Dict = 'amb@world_human_smoking@male@male_a@enter', Anim = 'enter', Flag = 49, Duration = 12700},
        {Type = 'Prop', Model = 'p_cs_joint_01', Stop = true},
        {Type = 'Playing', Boolean = false},
        {Type = 'Wait', Duration = 2500},
        {Type = 'ShakeCamera', Effect = 'FAMILY5_DRUG_TRIP_SHAKE', Intensity = 0.45},
        {Type = 'Walk', Style = 'move_dreyfuss'},
        {Type = 'ScreenEffect', Effect = 'DMT_flight_intro', Duration = 4600},
        {Type = 'ScreenEffect', Effect = 'DMT_flight', Duration = 350000},
        {Type = 'ScreenEffect', Effect = 'CamPushInNeutral', Duration = 1000},
        {Type = 'Walk', Stop = true},
        {Type = 'ScreenEffect', Stop = true},
        {Type = 'ShakeCamera', Stop = true},
    },
    Heroin = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Animation', Dict = 'amb@world_human_clipboard@male@idle_a', Anim = 'idle_c', Flag = 49, Duration = 5400},
        {Type = 'Playing', Boolean = false},
        {Type = 'Wait', Duration = 6500},
        {Type = 'ScreenEffect', Effect = 'DrugsMichaelAliensFightIn', Duration = 4500},
        {Type = 'ScreenEffect', Effect = 'DrugsMichaelAliensFight', Duration = 300000},
        {Type = 'ScreenEffect', Stop = true},
    },
    LSD = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Animation', Dict = 'mp_player_inteat@burger', Anim = 'mp_player_int_eat_burger', Flag = 49, Duration = 1000},
        {Type = 'Playing', Boolean = false},
        {Type = 'Wait', Duration = 7000},
        {Type = 'ScreenEffect', Effect = 'DrugsMichaelAliensFightIn', Duration = 3500},
        {Type = 'ScreenEffect', Effect = 'DrugsMichaelAliensFight', Duration = 300000},
        {Type = 'ScreenEffect', Stop = true}
    },
    Cocaine = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Animation', Dict = 'anim@mp_fm_event@intro', Anim = 'beast_transform', Flag = 49, Duration = 800},
        {Type = 'Playing', Boolean = false},
        {Type = 'Wait', Duration = 5500},
        {Type = 'ShakeCamera', Effect = 'HIGH_SPEED_VEHICLE_SHAKE', Intensity = 0.5},
        {Type = 'ScreenEffect', Effect = 'DrugsTrevorClownsFightIn', Duration = 3500},
        {Type = 'ScreenEffect', Effect = 'Rampage', Duration = 350000},
        {Type = 'ScreenEffect', Effect = 'DrugsTrevorClownsFightOut', Duration = 3000},
        {Type = 'ScreenEffect', Stop = true},
        {Type = 'ShakeCamera', Stop = true}
    },
    AlcoholBuzzed = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Prop', Model = 'prop_cs_beer_bot_01', Bone = 28422, Offset = vector3(0.01, 0.0, 0.0), Rotation = vector3(0.0, 0.0, 0.0)},
        {Type = 'Animation', Dict = 'amb@world_human_drinking@beer@male@idle_a', Anim = 'idle_c', Flag = 49, Duration = 5500},
        {Type = 'Prop', Model = 'prop_cs_beer_bot_01', Stop = true},
        {Type = 'Playing', Boolean = false},
        {Type = 'Wait', Duration = 1100},
        {Type = 'ScreenEffect', Effect = 'CamPushInNeutral', Duration = 1000},
    },
    AlcoholModerate = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Prop', Model = 'prop_cs_beer_bot_01', Bone = 28422, Offset = vector3(0.01, 0.0, 0.0), Rotation = vector3(0.0, 0.0, 0.0)},
        {Type = 'Animation', Dict = 'amb@world_human_drinking@beer@male@idle_a', Anim = 'idle_c', Flag = 49, Duration = 9500},
        {Type = 'Prop', Model = 'prop_cs_beer_bot_01', Stop = true},
        {Type = 'Playing', Boolean = false},
        {Type = 'Walk', Style = 'move_m@drunk@slightlydrunk'},
        {Type = 'ShakeCamera', Effect = 'DRUNK_SHAKE', Intensity = 0.85},
        {Type = 'TimeCycle', Effect = 'drug_wobbly'},
        {Type = 'Wait', Duration = 540000},
        {Type = 'ScreenEffect', Stop = true},
        {Type = 'ShakeCamera', Stop = true},
        {Type = 'TimeCycle', Stop = true},
        {Type = 'Walk', Stop = true}
    },
    AlcoholDrunk = {
        {Type = 'Playing', Boolean = true},
        {Type = 'Prop', Model = 'prop_cs_beer_bot_01', Bone = 28422, Offset = vector3(0.01, 0.0, 0.0), Rotation = vector3(0.0, 0.0, 0.0)},
        {Type = 'Animation', Dict = 'amb@world_human_drinking@beer@male@idle_a', Anim = 'idle_c', Flag = 49, Duration = 9500},
        {Type = 'Prop', Model = 'prop_cs_beer_bot_01', Stop = true},
        {Type = 'Walk', Style = 'move_m@drunk@verydrunk'},
        {Type = 'ShakeCamera', Effect = 'DRUNK_SHAKE', Intensity = 1.68},
        {Type = 'TimeCycle', Effect = 'drug_wobbly'},
        {Type = 'Playing', Boolean = false},
        {Type = 'Wait', Duration = 540000},
        {Type = 'ShakeCamera', Stop = true},
        {Type = 'TimeCycle', Stop = true},
        {Type = 'Walk', Stop = true}
    },
}